### ISSUE TITLE
Internet Connectivity

### ISSUE THREAD

**Issue by drhazrd** [sourcesync/MME_Apps#31] opened 2014-02-03 16:41 UTC
Right now the booth is doing the following:  If internet is in and out the program does not know how to act.  When internet is out the booth is getting stuck on the start screen, it will sit there for a very long time and sometimes not move to the enter email screen.  If it does go into the experience it will take the pictures finally and on the page that uploads the photo ( thanks page) the screen goes black.  Please let me know when we can carve out time to do this build.

**Comment by sourcesync** [comment] 2014-02-10 19:49
Hey, when you get a chance, can i get a download link for the last code ?  Also are you guys running Windows 7 or XP ?

**Comment by sourcesync** [comment] 2014-02-10 19:49
Also, ftp credentials and path are fine, but download link would be great !

**Comment by sourcesync** [comment] 2014-03-13 18:40
Closing this issue because its a duplicate of another.  Also all booth issues are now owned by MME_Hercules repo.

**Closed as completed by sourcesync** 2014-03-13 18:40 UTC
